@URL=http://localhost:8080/pessoa

@token =Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJBUEkgYXV0aGVudGljYXRpb24iLCJ1c2VybmFtZSI6ImRhbmllbEBlbWFpbC5jb20iLCJpYXQiOjE3MTMzMDg3MDUsImV4cCI6MTcxMzM0NDcwNSwiaXNzIjoiVVRGUFIifQ.28aqJUOpc8Jsrzy-EwKaaF7ni1SknZ1tRnOD7OIJBZM

### CREATE
POST {{URL}}
Content-Type: application/json

{
    "nome": "daniel",
    "email": "daniel@email.com",
    "senha": "12345678"
}

### GET ALL
GET {{URL}}
Authorization: {{token}}
### GET ID
GET {{URL}}/1
Authorization: {{token}}
### DELETE
DELETE {{URL}}/2
Authorization: {{token}}
### PUT
PUT {{URL}}/3
Authorization: {{token}}
Content-Type: application/json

{
    "nome": "nome1",
    "email": "nome1@hotmail.com",
}

### AUTH
POST http://localhost:8080/auth
Content-Type: application/json

{
    "username": "daniel@email.com",
    "password": "12345678"
}
